---
- hosts: all

  become: yes
  tasks:
  - name: install core packages
    apt:
      name:
        - nfs-common
        - vim
        - unzip
        - curl
        - wget
      update_cashe: yes

  